name: Release App

on:
  push:
    tags:
    - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 45

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Copy CI gradle.properties
        run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 11

      - name: Set gradle properties
        run: |
          echo "ORG_GRADLE_PROJECT_VERSION_CODE=$GITHUB_RUN_NUMBER" >> $GITHUB_ENV
          echo "ORG_GRADLE_PROJECT_BUILD_NUMBER=$GITHUB_RUN_NUMBER" >> $GITHUB_ENV

      - name: Download Keystore & Gcloud Service Key
        run: |
          echo ${{ secrets.UPLOAD_KEYSTORE }} | base64 --decode > upload.keystore
          echo "${{ secrets.GCLOUD_SERVICE_ACCOUNT_JSON }}" | base64 --decode --ignore-garbage > gcloud_service_key.json

      - name: Build app
        run: ./gradlew :app:bundleRelease
        env:
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}

      - name: Deploy to Play Store
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJson: gcloud_service_key.json
          packageName: com.practice.android_app_2022
          releaseFiles: app/build/outputs/bundle/release/app-release.aab
          track: internal
          status: completed
